name: Maven CI
on: [push]
jobs:
  maven:
    runs-on: ubuntu-latest
    steps:
    - name: Setup JDK
      uses: actions/setup-java@v3.14.1
      with:
        java-version: 17
        distribution: adopt
    - name: Checkout
      uses: actions/checkout@v4.2.2
    - name: Build the project
      run: mvn package
    - name: Build the examples
      run: mvn package -DbuildExamples=true
    -  name: Upload build artifact
       uses: actions/upload-artifact@v4.5.0
       with:
          name: vcd4j
          path: target/*
      
